---
- name: Update and Upgrade Ubuntu
  hosts: localhosts
  remote_user: root

  tasks:
  - name: Run update
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes
